package com.cerebus.create_screen.presentation

data class CreateScreenStrings(
    val back: String,
    val importDeck: String,
    val myDecks: String,
    val noDecksYet: String,
    val createDeckTitle: String,
    val addCover: String,
    val editCover: String,
    val deckNameLabel: String,
    val create: String,
    val cancel: String,
    val chooseSource: String,
    val chooseFromGallery: String,
    val takePhoto: String,
    val close: String,
    val delete: String,
    val export: String,
    val selectedCount: String,
    val exportLimitHint: String,
    val confirmDeleteDecksTitle: String,
    val confirmDeleteDecksMessage: String,
    val confirmImportDeckReplacementTitle: String,
    val confirmImportDeckReplacementMessage: String,
    val importDeckReplaceSummary: String,
    val importDeckAddMissingSummary: String,
    val replaceDeck: String,
    val addMissingCards: String,
    val deckCreatedTemplate: String,
    val addCards: String,
    val noCover: String,
)
