package com.cerebus.create_screen.presentation

data class DeckScreenStrings(
    val back: String,
    val exportDeck: String,
    val addCard: String,
    val startTraining: String,
    val addCardTitle: String,
    val editCardTitle: String,
    val cards: String,
    val editName: String,
    val editCover: String,
    val addCover: String,
    val chooseSource: String,
    val chooseFromGallery: String,
    val takePhoto: String,
    val create: String,
    val save: String,
    val cancel: String,
    val close: String,
    val delete: String,
    val selectedCount: String,
    val confirmDeleteCardsTitle: String,
    val confirmDeleteCardsMessage: String,
    val deckNameLabel: String,
    val cardNameLabel: String,
    val noCover: String,
    val unnamedDeck: String,
)
